<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SuiteOneCaseTwo"
           tests="2"
           failures="2"
           errors="0"
           skipped="0"
           time="141.103">
  <properties />
            <testcase name="SuiteOneCaseTwoTest" time="0.172" classname="com.stta.SuiteOne.SuiteOneCaseTwo">
                <failure type="org.openqa.selenium.WebDriverException"
                  message="Reached error page: about:neterror?e=dnsNotFound&amp;u=http%3A//only-testing-blog.blogspot.com/2014/04/calc.html&amp;c=UTF-8&amp;f=regular&amp;d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20only-testing-blog.blogspot.com. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 172 milliseconds
Build info: version: &apos;unknown&apos;, revision: &apos;2aa21c1&apos;, time: &apos;2016-08-02 14:59:43 -0700&apos;
System info: host: &apos;LAPTOP-T6NJ110T&apos;, ip: &apos;192.168.89.2&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;x86&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_101&apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=12768, browserVersion=50.1.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 12164ba7-65e6-4bc2-ab33-17b47738bfa5"
              >
<![CDATA[org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=dnsNotFound&u=http%3A//only-testing-blog.blogspot.com/2014/04/calc.html&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20find%20the%20server%20at%20only-testing-blog.blogspot.com. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 172 milliseconds
Build info: version: 'unknown', revision: '2aa21c1', time: '2016-08-02 14:59:43 -0700'
System info: host: 'LAPTOP-T6NJ110T', ip: '192.168.89.2', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161208153507, version=, platform=XP, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, processId=12768, browserVersion=50.1.0, platformVersion=10.0, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, takesElementScreenshot=true, platformName=windows_nt}]
Session ID: 12164ba7-65e6-4bc2-ab33-17b47738bfa5
  sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
  org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:683)
  org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:331)
  com.stta.SuiteOne.SuiteOneCaseTwo.SuiteOneCaseTwoTest(SuiteOneCaseTwo.java:84)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:746)
  org.testng.TestRunner.run(TestRunner.java:600)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1260)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
  org.testng.TestNG.runSuites(TestNG.java:1104)
  org.testng.TestNG.run(TestNG.java:1076)
  org.testng.TestNG.privateMain(TestNG.java:1405)
  org.testng.TestNG.main(TestNG.java:1374)
]]>
      </failure>

          </testcase>
            <testcase name="SuiteOneCaseTwoTest" time="140.931" classname="com.stta.SuiteOne.SuiteOneCaseTwo">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.stta.SuiteOne.SuiteOneCaseTwo.SuiteOneCaseTwoTest(SuiteOneCaseTwo.java:87)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:746)
  org.testng.TestRunner.run(TestRunner.java:600)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1260)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
  org.testng.TestNG.runSuites(TestNG.java:1104)
  org.testng.TestNG.run(TestNG.java:1076)
  org.testng.TestNG.privateMain(TestNG.java:1405)
  org.testng.TestNG.main(TestNG.java:1374)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
